### ISSUE TITLE
Arrow tips in lines (->-, put arrow) doesn't work at all

### ISSUE THREAD

**Issue by TorbjornT** [fruchart/tikz-optics#1]
I know you say in the manual that these things are under development/likely to change, but at the moment they do not appear to work at all with an up-to-date TeX Live 2016 (TikZ 3.0.1a, `tikz-optics` v0.2.2).

For example, 
```
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{optics}
\begin{document}
\begin{tikzpicture}[use optics]
\draw[->-={at=0.25}] (0,0) -- (1, 0);
\end{tikzpicture}
\end{document}
```

throws

```
! Undefined control sequence.
\pgfkeys@code #1\pgfeov ->\letcs 
                                 \reserved {pgfk@\pgfkeyscurrentpath /unknow...
l.9 \draw[->-={at=0.25}]
                         (0,0) -- (1, 0);
?
```

and with

```
\begin{tikzpicture}[use optics]
\draw[put arrow={at=0.25}] (0,0) -- (1, 0);
\end{tikzpicture}
```

(or `\draw [->-] (0,0) -- (1, 0);`) I get

```
! Package pgfkeys Error: I do not know the key '/pgf/decoration/\pgfkeyscurrent
name ' and I am going to ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9 \draw[put arrow={at=0.25}] (0,0) -- (1, 0);
                                               
? 
```

**Comment by fruchart** [comment]
Thanks for the report!

I think the only problem is some missing packages (which should indeed be called from the tikz-optics code). I can reproduce the behavior your encounter, but everything works fine with, say,

    \documentclass{standalone}
    \usepackage{tikz}
    \usetikzlibrary{decorations,decorations.markings}
    \usepackage{etoolbox}
    \usetikzlibrary{optics}
    \begin{document}
    \begin{tikzpicture}[use optics]
    \draw[put arrow={at=0.25}] (0,0) -- (1,1);
    \end{tikzpicture}
    \end{document}

Does that solve the issue for you?

**Comment by TorbjornT** [comment]
Indeed it does, thanks!

**Comment by TorbjornT** [comment]
I forgot to close this. But I assume that in the next update you'll add the missing dependencies to the library.
