### ISSUE TITLE
Inconsistent scaling

### ISSUE THREAD

**Issue by genodeftest** [fruchart/tikz-optics#3]
Steps to reproduce:
1. use the latest version of texlive
2. in a tikz environment, use several tikz-optics nodes together with basic tikz nodes.
3. set "scale=.5" or some other scale in tikzpicture options such as
```
\begin{tikzpicture}[use optics, scale=.5]
    …
\end{tikzpicture}
```

What happens:
"scale" scales distances and pure tikz nodes such as path or rectangle, but it does not "object height", "slit height", focal length distances, "generic lamp", …

What should happen:
tikz-optics nodes should be scaled accordingly.

Version info:
pdflatex.exe --version
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/W32TeX)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty. Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.29; using libpng 1.6.29
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 3.04

tikz-optics: 43466 (0.2.3)
pgf: 44231 (3.0.1a)

**Comment by fruchart** [comment]
I think this is the intended behavior. In tikz, `scale` does not change the node sizes (see e.g. https://tex.stackexchange.com/a/26852/3968). You can apply a style to every node to make it work, if you need: 
![scaling](https://user-images.githubusercontent.com/13440379/31301600-6ca65f9e-aafb-11e7-88c3-7b9d8e4cf974.png)
[[picture source]](https://gist.github.com/fruchart/1c56616ac4c6294cec1ed34dc171f6fc) (the red line is a `\draw` command, which is affected by `scale=`). 

However, my advice would be to avoid `scale` as much as possible.
