### ISSUE TITLE
Add code to simplify intersecting paths with nodes

### ISSUE THREAD

**Issue by genodeftest** [fruchart/tikz-optics#5]
Currently, one has to use quite some math to intersect light rays (paths) with lenses or to make them stop at e.g. a sensor. It would be nice to have basic raytracing features such as starting light at a given position + angle and tikz-optics would propagate the ray accordingly.

**Comment by fruchart** [comment]
Thanks for the suggestion! What exactly do you have in mind?

Tikz already provides an interface for intersection computations, so you can do things like

```latex
\begin{tikzpicture}[use optics]
\coordinate (S) at (-3cm,0);
\node[cross out,draw] at (S) {};
\node[lens] (L) at (0,0) {};
\node[sensor line] (CCD) at (5cm,0) {};

\draw[red] (S) -- (intersection of L.north--L.south and S--[shift={(10:1cm)}]S) coordinate (I)
               -- (intersection of CCD.north west--CCD.south west and I--[shift={(-15:1cm)}]I);

\end{tikzpicture}
```
which produces
![draw_light_intersections](https://user-images.githubusercontent.com/13440379/31302208-3a9d6128-ab00-11e7-8678-817ce08b0e9c.png)

The syntax is a bit verbose, but I am not sure if it is possible to significantly simplify it.

As for actual (physically correct) ray propagation, I don't think latex is the right tool for that!

**Comment by genodeftest** [comment]
> `intersection of CCD.north west--CCD.south west and […]`

exactly that did not work for me. Will have to try again, looks like the bug is on my side.
